'\" t
.\"     Title: ypbind
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 08/03/2020
.\"    Manual: ypbind-mt
.\"    Source: ypbind-mt
.\"  Language: English
.\"
.TH "YPBIND" "8" "08/03/2020" "ypbind-mt" "ypbind\-mt"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ypbind \- NIS binding process
.SH "SYNOPSIS"
.HP \w'\fBypbind\fR\ 'u
\fBypbind\fR [\-c] [\-d | \-debug] [\-verbose] [\-n | \-forground] [\-broadcast] [\-broken\-server] [\-ypset] [\-ypsetme] [\-no\-ping] [\-f\ \fIconfigfile\fR] [\-local\-only] [\-ping\-interval\ \fIping\-interval\fR] [\-rebind\-interval] [\-no\-dbus]
.HP \w'\fBypbind\fR\ 'u
\fBypbind\fR \-\-version
.SH "DESCRIPTION"
.PP
\fBypbind\fR
finds the server for NIS domains and maintains the NIS binding information\&. The client (normally the NIS routines in the standard C library) could get the information over RPC from
\fBypbind\fR
or read the binding files\&. The binding files resides in the directory
/var/yp/binding
and are conventionally named
\fB[domainname]\&.[version]\fR\&. The supported versions are 1 and 2\&. There could be several such files since it is possible for an NIS client to be bound to more than one domain\&.
.PP
After a binding has been established,
\fBypbind\fR
will send YPPROC_DOMAIN requests to the current NIS server at 20 seconds intervals\&. If it doesn\*(Aqt get an response or the NIS server reports that he doesn\*(Aqt have this domain any longer,
\fBypbind\fR
will search for a new NIS server\&. All 15 minutes
\fBypbind\fR
will check to see if the current NIS server is the fastest\&. If it find a server which answers faster, it will switch to this server\&. You could tell
\fBypbind\fR
to use network broadcasts to find a new server, what is insecure, or you could give it a list of known secure servers\&. In this case
\fBypbind\fR
will send a ping to all servers and binds to first one which answers\&.
.PP
Unless the option
\fB\-debug\fR
is used, ypbind detaches itself from the controlling terminal and puts itself into background\&.
\fBypbind\fR
uses
\fBsyslog\fR(3)
for logging errors and warnings\&. At startup or when receiving signal SIGHUP,
\fBypbind\fR
parses the file
/etc/yp\&.conf
and tries to use the entries for its initial binding\&.
.PP
A broadcast entry in the configuration file will overwrite a ypserver/server entry and a ypserver/server entry broadcast\&. If all given server are down,
\fBypbind\fR
will
\fBnot\fR
switch to use broadcast\&.
\fBypbind\fR
will try at first
/etc/hosts
and then
\fBDNS\fR
for resolving the hosts names from
/etc/yp\&.conf\&. If
\fBypbind\fR
couldn\*(Aqt reconfigure the search order, it will use only
\fBDNS\fR\&. If
\fBDNS\fR
isn\*(Aqt available, you could only use IP\-addresses in
/etc/hosts\&.
\fBypbind\fR
could only reconfigure the search order with glibc 2\&.x\&. If the
\fB\-broadcast\fR
option is specified,
\fBypbind\fR
will ignore the configuration file\&. If the file does not exist or if there are no valid entries,
\fBypbind\fR
exit\&.
.PP
This
\fBypbind\fR
version listens for DBUS messages from NetworkManager\&. If no NetworkManager is running at startup,
\fBypbind\fR
will behave as usual and assumes there is a working network connection\&. If NetworkManager is running on the system, ypbind will only search and provide NIS informations, if NetworkManager tells that a network connection is available\&. If NetworkManager establishes a connection,
\fBypbind\fR
will reread all configuration files, registers at the local portmapper and try to search NIS servers\&. If NetworkManager drops a connection,
\fBypbind\fR
will unregister from portmapper\&.
.SH "OPTIONS"
.PP
\fB\-broadcast\fR
.RS 4
Send a broadcast to request the information needed to bind to a specific NIS server\&. With this option,
/etc/yp\&.conf
will be ignored\&.
.RE
.PP
\fB\-ypset\fR
.RS 4
Allow
\fBroot\fR
from any remote machine to change the binding for a domain via the
\fBypset\fR(8)
command\&. By default, no one can change the binding\&. This option is really insecure\&. If you change a binding for a domain, all the current known servers for this domain will be forgotten\&. If the new server goes down,
\fBypbind\fR
will use the old searchlist\&.
.RE
.PP
\fB\-ypsetme\fR
.RS 4
The same as
\fB\-ypset\fR, but only
\fBroot\fR
on the local machine is allowed to change the binding\&. Such requests are only allowed from
\fBloopback\fR\&.
.RE
.PP
\fB\-c\fR
.RS 4
\fBypbind\fR
only checks if the config file has syntax errors and exits\&.
.RE
.PP
\fB\-d\fR, \fB\-debug\fR
.RS 4
starts
\fBypbind\fR
in debug mode\&.
\fBypbind\fR
will not put itself into background, and error messages and debug output are written to standard error\&.
.RE
.PP
\fB\-n\fR, \fB\-foreground\fR
.RS 4
\fBypbind\fR
will not put itself into backgroun\&.
.RE
.PP
\fB\-v\fR, \fB\-verbose\fR
.RS 4
Causes
\fBypbind\fR
to syslog(2) any and all changes in the server its bound to\&.
.RE
.PP
\fB\-broken\-server\fR
.RS 4
Lets
\fBypbind\fR
accept answers from servers running on an illegal port number\&. This should usually be avoided, but is required by some
\fBypserv\fR(8)
versions\&.
.RE
.PP
\fB\-no\-ping\fR
.RS 4
\fBypbind\fR
will not check if the binding is alive\&. This option is for use with dialup connections to prevent
\fBypbind\fR
from keeping the connection unnecessarily open or causing auto\-dials\&.
.RE
.PP
\fB\-f\fR configfile
.RS 4
\fBypbind\fR
will use
\fBconfigfile\fR
and not
/etc/yp\&.conf
.RE
.PP
\fB\-local\-only\fR
.RS 4
\fBypbind\fR
will only bind to the loopback device and is not reachable from a remote network\&.
.RE
.PP
\fB\-i\fR, \fB\-ping\-interval\fR ping\-interval
.RS 4
The default value for
\fBypbind\fR
to check, if a NIS server is still reachable, is 20 seconds\&. With this options another frequency in seconds can be specified\&.
.RE
.PP
\fB\-r\fR, \fB\-rebind\-interval\fR
.RS 4
The default value for
\fBypbind\fR
to search for the fastest NIS server is 900 seconds (15 minutes)\&. With this options another frequency in seconds can be specified\&.
.RE
.PP
\fB\-no\-dbus\fR
.RS 4
Disables DBUS support if compiled in\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Prints the version number
.RE
.SH "FILES"
.PP
/etc/yp\&.conf
.RS 4
configuration file\&.
.RE
.PP
/var/yp/binding/[domainname]\&.[version]
.RS 4
binding file containing information about each NIS domain\&.
.RE
.PP
/var/run/ypbind\&.pid
.RS 4
contains the process id of the currently running
\fBypbind\fR
master process\&.
.RE
.SH "SEE ALSO"
.PP
\fBsyslog\fR(3),
\fBdomainname\fR(1),
\fByp.conf\fR(5),
\fBypdomainname\fR(8),
\fBypwhich\fR(1),
\fBypserv\fR(8),
\fBypset\fR(8)
.SH "AUTHOR"
.PP
\fBypbind\-mt\fR
was written by Thorsten Kukuk <kukuk@thkukuk\&.de>\&.
